### ISSUE TITLE
App Icon

### ISSUE THREAD

**Issue by avojak** [avojak/vee#1]
@Suzie97 - This is the repo where I will be continuing work on developing my own Game Boy emulator. This project is mostly for my own curiosity and desire to learn about emulation. It wouldn't have any functionality not present in Replay, but the goal is to create a Game Boy emulator written in Vala. I alluded to this in the Replay repository, but wanted to ask explicitly here if it was ok for me to continue using the icon that you developed, but in this new project?

**Comment by Suzie97** [comment]
Yeah, sure you can use the icon. I'm happy to contribute. :))

And I think, technically now the icon is yours as its in your repo under your copyright. I might be wrong tho :P

**Comment by avojak** [comment]
Yea I think you're right, still wanted to check with you though! Thanks again for making a great icon!
